[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x", "python3"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3